version: 2
jobs:
  build:
    # Ref: https://mmhaskell.com/blog/2018/4/25/dockerizing-our-haskell-app
    docker:
    - image: haskell:8.4
    steps:
    - run: apt update
    - run: stack upgrade
    - run: "echo 'tcp     6       TCP' > /etc/protocols"
    - run: "stack config --system-ghc set system-ghc --global true"
    - checkout

    - restore_cache:
        keys:
        - 'dependencies-{{ checksum "stack.yaml" }}-{{ checksum "typesafe-precure.cabal" }}'
        - 'dependencies-'
    - save_cache:
        key: 'dependencies-{{ checksum "stack.yaml" }}-{{ checksum "typesafe-precure.cabal" }}'
        paths:
        - ~/.stack/
        - .stack-work/
    - run: stack --compiler=ghc-8.4.4 --no-terminal test --pedantic
