version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - org-global
jobs:
  build:
    # Ref: https://mmhaskell.com/blog/2018/4/25/dockerizing-our-haskell-app
    docker:
    - image: haskell:8.10.4
      auth:
        username: '$DOCKERHUB_USERNAME'
        password: '$DOCKERHUB_PASSWORD'
    steps:
    - run: apt update
    - run: apt-get install locales locales-all -y
    - run: locale-gen en_US.UTF-8
    - run: stack upgrade
    - run: "echo 'tcp     6       TCP' > /etc/protocols"
    - run: "stack config --system-ghc set system-ghc --global true"
    - checkout

    - restore_cache:
        keys:
        - 'dependencies-{{ checksum "stack.yaml.lock" }}-{{ checksum "typesafe-precure.cabal" }}'
        - 'dependencies-'
    - run:
        command: stack --compiler=ghc-8.10.4 --no-terminal test --pedantic
        environment:
          LANG: en_US.UTF-8
          LANGUAGE: en_US:en
          LC_ALL: en_US.UTF-8
    - save_cache:
        key: 'dependencies-{{ checksum "stack.yaml.lock" }}-{{ checksum "typesafe-precure.cabal" }}'
        paths:
        - ~/.stack/
        - .stack-work/
